name: 'Install CNS11643 fonts'
description: 'Install CNS11643 fonts'
author: hms5232
branding:
  icon: type
  color: yellow
inputs:
  kai:
    description: 'Install 正楷體 or not'
    required: false
    default: 'true'
  sung:
    description: 'Install 正宋體 or not'
    required: false
    default: 'true'
runs:
  using: "composite"
  steps:
    - name: Init environment
      run: ${{ github.action_path }}/init.sh
      shell: bash
    - run: |
        echo "::group::download and unzip"
        ${{ github.action_path }}/download.sh || echo "Download completed"
        echo "::endgroup::"
      shell: bash
    - name: Prepare kai font
      run: ${{ github.action_path }}/copy.sh kai
      shell: bash
      if:  ${{ inputs.kai == 'true' }}
    - name: Prepare sung font
      run: ${{ github.action_path }}/copy.sh sung
      shell: bash
      if:  ${{ inputs.sung == 'true' }}
    - run: |
        echo "::group::update fonts"
        ${{ github.action_path }}/install.sh
        echo "::endgroup::"
      shell: bash
    - name: Clear files
      run: ${{ github.action_path }}/clear.sh
      shell: bash
