name: 'Install CNS11643 fonts'
description: 'Install CNS11643 fonts'
author: hms5232
branding:
  icon: type
  color: yellow
inputs:
  kai:
    description: 'Install 正楷體 or not'
    required: false
    default: true
  sung:
    description: 'Install 正宋體 or not'
    required: false
    default: true
defaults:
  run:
    shell: bash
runs:
  using: "composite"
  steps:
    - run: ./init.sh
      shell: bash
    - run: ./download.sh || echo "Download completed"
      shell: bash
    - run: ./copy.sh kai
      shell: bash
      if:  ${{ github.event.inputs.kai == 'true' }}
    - run: ./copy.sh sung
      shell: bash
      if:  ${{ github.event.inputs.sung == 'true' }}
    - run: ./install.sh
      shell: bash
    - run: ./clear.sh
      shell: bash
