name: 'Install CNS11643 fonts'
description: 'Install CNS11643 fonts'
author: hms5232
branding:
  icon: type
  color: yellow
inputs:
  kai:
    description: 'Install 正楷體 or not'
    required: false
    default: 'true'
  sung:
    description: 'Install 正宋體 or not'
    required: false
    default: 'true'
  download-flag:
    description: 'Add flag(s) when use wget'
    required: false
    default: '-nv'
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/init.sh
      shell: bash
    - run: |
        echo "::group::download and unzip"
        ${{ github.action_path }}/download.sh -f "${{ inputs.download-flag }}" || echo "Download completed"
        echo "::endgroup::"
      shell: bash
    - run: ${{ github.action_path }}/copy.sh kai
      shell: bash
      if:  ${{ inputs.kai == 'true' }}
    - run: ${{ github.action_path }}/copy.sh sung
      shell: bash
      if:  ${{ inputs.sung == 'true' }}
    - run: |
        echo "::group::update fonts"
        ${{ github.action_path }}/install.sh
        echo "::endgroup::"
      shell: bash
    - run: ${{ github.action_path }}/clear.sh
      shell: bash
