name: 'CJK-Fonts-Action'
description: 'Install CJK font(s) (currently Source Han Sans) for GitHub Action.'
author: hms5232, RisingInIris2017
branding:
  icon: type
  color: yellow
inputs:
  download-flag:
    description: 'Flag(s) of wget. '
    required: false
    default: '-nv'
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/init.sh
      shell: bash
    - run: |
        echo "::group::download and unzip"
        ${{ github.action_path }}/download.sh -f "${{ inputs.download-flag }}" || echo "Download completed"
        echo "::endgroup::"
      shell: bash
    - run: ${{ github.action_path }}/copy.sh
      shell: bash
    - run: |
        echo "::group::update fonts"
        ${{ github.action_path }}/install.sh
        echo "::endgroup::"
      shell: bash
    - run: ${{ github.action_path }}/clear.sh
      shell: bash
